### ISSUE TITLE
Database dan Path error

### ISSUE THREAD

**Issue by L007** [OpenSID/wpsid-shortcode#1]
Database gagal terkoneksi dan Path SID salah, padahal sudah benar
mohon pencerahannya untuk langkah-langkah installasi setelah activate plugin
terimakasih

![image](https://user-images.githubusercontent.com/15906655/42409122-d82ecf7c-81ff-11e8-9da5-6be51bf96e6d.png)

**Comment by eddieridwan** [comment]
Masalah penggunaan sebaiknya ditanyakan dulu di https://www.facebook.com/groups/OpenSID/. 

Issue dibatasi khusus untuk masalah yg terbukti memerlukan perbaikan script.

**Comment by hyuzea** [comment]
sudah diperbaiki.
