### ISSUE TITLE
Perlu dibuatkan tutorial instalasi

### ISSUE THREAD

**Issue by hyuzea** [OpenSID/wpsid-shortcode#3]
Apakah sebaiknya repo ini dipush juga ke wordpress direktori? dengan nama baru misalnya "wpsid-shortcode-update"
atau tetap di sini dan buat tutorial instalasi manual

**Comment by eddieridwan** [comment]
@suphm di repo ini saja. Ini repo lengkap. Setingkat dengan OpenSID. Supaya bisa dikelola secara terpisah. Panduan sebaiknya ditulis di https://github.com/OpenSID/wpsid-shortcode/wiki. 

Dan proses rilis juga sebaiknya menggunakan fitur releases yg ada di github, yaitu di https://github.com/OpenSID/wpsid-shortcode/releases.

Sehingga `readme` di halaman muka https://github.com/OpenSID/wpsid-shortcode dapat lebih bersifat penjelasan umum.
